#!/bin/bash

apt install -y zip

CWD="$(pwd)"

cd ClientService/Nodegem.ClientService

if [[ "$OSTYPE" == "linux-gnu"* ]]; then
    echo "Building Client Services..."
    echo 'Building Windows'
    dotnet publish -c release -r win-x64 /p:PublishSingleFile=true -o $CWD/binaries/client_service/win64 -v q
    echo 'Building OSX'
    dotnet publish -c release -r osx-x64 /p:PublishSingleFile=true -o $CWD/binaries/client_service/osx -v q
    echo 'Building Linux'
    dotnet publish -c release -r linux-x64 /p:PublishSingleFile=true -o $CWD/binaries/client_service/linux -v q
    echo 'Building Linux Arm'
    dotnet publish -c release -r linux-arm /p:PublishSingleFile=true -o $CWD/binaries/client_service/linux-arm32 -v q 
    echo 'Building Linux Arm 64 bit'
    dotnet publish -c release -r linux-arm64 /p:PublishSingleFile=true -o $CWD/binaries/client_service/linux-arm64 -v q

    echo "Building Web Api..."

elif [[ "$OSTYPE" == "msys" ]]; then
    echo "Building Client Services..."
    echo 'Building Windows'
    dotnet publish -c release -r win-x64 //p:PublishSingleFile=true -o $CWD/binaries/client_service/win64 -v q
    echo 'Building OSX'
    dotnet publish -c release -r osx-x64 //p:PublishSingleFile=true -o $CWD/binaries/client_service/osx -v q
    echo 'Building Linux'
    dotnet publish -c release -r linux-x64 //p:PublishSingleFile=true -o $CWD/binaries/client_service/linux -v q
    echo 'Building Linux Arm'
    dotnet publish -c release -r linux-arm //p:PublishSingleFile=true -o $CWD/binaries/client_service/linux-arm32 -v q
    echo 'Building Linux Arm 64 bit'
    dotnet publish -c release -r linux-arm64 //p:PublishSingleFile=true -o $CWD/binaries/client_service/linux-arm64 -v q

    echo "Building Web Api..."
fi

mkdir -p $CWD/compressed/client_service
cd $CWD/compressed/client_service

echo "Compressing client service files..."

cd $CWD/binaries/client_service/win64
zip -r $CWD/compressed/client_service/nodegem-win64.zip .
cd $CWD/compressed/client_service

tar -czf nodegem-osx64.tar.gz -C $CWD/binaries/client_service/osx .
tar -czf nodegem-linux64.tar.gz -C $CWD/binaries/client_service/linux .
tar -czf nodegem-linux-arm32.tar.gz -C $CWD/binaries/client_service/linux-arm32 .
tar -czf nodegem-linux-arm64.tar.gz -C $CWD/binaries/client_service/linux-arm64 .

mkdir -p $CWD/compressed/webapi
cd $CWD/compressed/webapi

echo "Compressing web api files..."

cd $CWD