#!/bin/bash

aws --endpoint=${S3_ENDPOINT} s3 sync binaries s3://${BUCKET_NAME}/releases/latest --acl public-read

if [[ ! -z "${CI_COMMIT_TAG}" ]]; then
    aws --endpoint=${S3_ENDPOINT} s3 sync binaries s3://${BUCKET_NAME}/releases/${CI_COMMIT_TAG} --acl public-read
fi